language: python

python:
  - '3.5'
  - '3.6'

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  - DB_NAME=raster_test PYTHONPATH=$PYTHONPATH:$PWD DJANGO_SETTINGS_MODULE=tests.testproj.settings

before_script:
  - psql -c 'create database raster_test' -U postgres
  - psql -c 'create extension postgis' -U postgres -d raster_test

install:
  - pip install django==2.1.9
  - pip install -e .
  - pip install psycopg2-binary==2.7.7
  - pip install flake8==3.7.7
  - pip install isort==4.3.15
  - pip install coverage==4.5.3
  - pip install coveralls
  - pip install mock

script: coverage run --include="raster/*" $(which django-admin.py) test

after_success: coveralls

notifications:
  email: false
