# Generated by Django 2.2.4 on 2019-08-05 07:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasterWithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('name', models.TextField()),
            ],
        ),
    ]
